export const MSG_ADD_TO_CART = "Mua hàng thành công!"
export const MSG_UPDATE_TO_CART = "Cập nhật giỏ hàng thành công!"
export const MSG_DELETE_PRODUCT_IN_CART_SUCCESS = "Xóa sản phẩm khỏi giỏ hàng thành công"
export const MSG_CART_EMPTY = "Chưa có sản phẩm trong giỏ hàng"
export const MSG_WELCOME = "Chào mừng đến với giỏ hàng"
